### ISSUE TITLE
Luarocks Dependency: api-gateway-cachemanager

### ISSUE THREAD

**Issue by yoshida-mediba** [adobe-apiplatform/api-gateway-aws#16] opened 2016-11-07 05:39 UTC
```
2016/11/07 14:36:16 [error] 508#508: *1435 lua entry thread aborted: runtime error: ...ocal/share/lua/5.1/api-gateway/aws/AWSIAMCredentials.lua:13: module 'api-gateway.cache.cache' not found:
	no field package.preload['api-gateway.cache.cache']
	no file './api-gateway/cache/cache.lua'
	no file '/usr/share/luajit-2.0.3/api-gateway/cache/cache.lua'
	no file '/usr/local/share/lua/5.1/api-gateway/cache/cache.lua'
	no file '/usr/local/share/lua/5.1/api-gateway/cache/cache/init.lua'
	no file '/usr/share/lua/5.1/api-gateway/cache/cache.lua'
	no file '/usr/share/lua/5.1/api-gateway/cache/cache/init.lua'
	no file '/var/www/watashineko/api/v1/api-gateway/cache/cache.lua'
	no file './api-gateway/cache/cache.so'
	no file '/usr/local/lib/lua/5.1/api-gateway/cache/cache.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/api-gateway/cache/cache.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './api-gateway.so'
	no file '/usr/local/lib/lua/5.1/api-gateway.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/api-gateway.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

https://luarocks.org/modules/adobe-api-platform/lua-api-gateway-aws

**Comment by ddragosd** [comment] 2017-01-11 01:38
@yoshida-mediba in case you didn't upload it yourself by now here it is: http://luarocks.org/modules/adobe-api-platform/lua-api-gateway-cachemanager

**Comment by mrgonza78** [comment] 2017-06-01 15:46
is this probably a duplicate of https://github.com/adobe-apiplatform/api-gateway-aws/issues/20 ?

**Comment by ddragosd** [comment] 2017-06-01 17:55
closing it as duplicate since @mrgonza78 has validated it works.

**Closed as completed by ddragosd** 2017-06-01 17:55 UTC
